### ISSUE TITLE
components defined inside of TypeScript namespaces are not processed

### ISSUE THREAD

**Issue by Enteleform** [orenelbaum/babel-plugin-solid-undestructure#3]
### Expected
Components defined inside of a TypeScript namespace will be processed and have the `undestructure` transformations applied.

### Actual
Transformations are not applied, resulting in a `compile time function` warning and `Uncaught TypeError`.

&nbsp;  
## Stack Trace

```log
index.js:2 The "component" function is a compile time function.
  It was called at runtime, which means that either babel-plugin-solid-undestructure wasn't applied.
  Make sure to configure babel-plugin-solid undestructure correctly or remove the "component" function.

dev.js:530 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at devComponent (dev.js:530:26)
    at createComponent (dev.js:1221:10)
    at App (App.tsx:33:2)
    at hmrCompWrapper (@solid-refresh:16:18)
    at dev.js:98:53
    at dev.js:170:29
    at runUpdates (dev.js:788:12)
    at createRoot (dev.js:170:12)
    at render (dev.js:96:3)
    at index.tsx:6:1
```

&nbsp;  
## Reproduction

https://codesandbox.io/s/github/enteleform-codesandbox/0002--Solid--Undestructure?file=/src/App.tsx

**Comment by orenelbaum** [comment]
Thanks for opening an issue! I'll look into it.

**Comment by orenelbaum** [comment]
Fixed!

**Comment by Enteleform** [comment]
Awesome, thanks Oren!
